### ISSUE TITLE
don't use inline styling

### ISSUE THREAD

**Issue by rimmesbe** [IHattem/prj-rev-bwfs-dasmoto#2]
You should basically never be using inline styling anymore now that we have css stylesheets. Inline styling is basically impossible to overwrite and is inefficient. 

https://github.com/IHattem/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/index.html#L13

**Comment by IHattem** [comment]
Noted! I will study up on my stylesheet skills.
