### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [IHattem/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on the project, the site looks good. You used some good techniques here. Take a look at the issues I created as they will point out some important techniques you should start using. Project will be growing in size from here on out and being organized and efficient will be very important. Here is a good article with some tips as well: 
http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by IHattem** [comment]
Thanks for the article and feedback! I bookmarked it for future reference.
